<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Phonebook' => 'Telefonliste',
    '<strong>Phonebook</strong> configuration' => '<strong>Telefonlisten</strong> konfiguration',
	'Welcome to the admin area. I want to add some settings, but i need more time!' => 'Willkommen im Admin Bereich. Ich möchte hier noch Einstellungesmöglichkeiten hinzufügen, jedoch benötige ich noch mehr Zeit!',
	'A simple phonebook with Ajax Search' => 'Eine einfache Telefonliste mit Ajax Suche',
	
    
];
